version: '3'

services:
  server:
    build: /server
    image: server
    container_name: server
    mem_limit: 1048m
    ports:
      - 8081:8081
      - 8082:8082
    cpus: 1
    restart: always
  client:
    build: /client
    image: client
    container_name: client
    mem_limit: 1048m
    ports:
      - 8083:8083
    cpus: 1
    restart: always
