FROM adoptopenjdk/openjdk8:ubi

WORKDIR /

# tạo folder
RUN mkdir -p /data/projects/app
RUN mkdir -p /data/projects/app/file

# coppy file tại thư mục chạy cậu lệnh, đến thư mục với tên file trong image
COPY target/server-1.0-SNAPSHOT.jar /data/projects/app/app.jar
ENV spring_profiles_active=Local
# start
CMD ["java","-jar", "/data/projects/app/app.jar"]
